# Generated by Django 4.2.1 on 2023-06-15 21:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(max_length=300, verbose_name='Описание')),
                ('slug', models.SlugField()),
                ('date', models.DateField(blank=True, null=True)),
                ('deadline', models.CharField(choices=[('', 'Выбрать категорию...'), ('Где поесть', 'Где поесть'), ('Продукты', 'Продукты'), ('Банкоматы', 'Банкоматы')], default='Выбрать категорию...', max_length=20)),
                ('lattitude', models.FloatField(max_length=20, validators=[django.core.validators.MinValueValidator(59.8), django.core.validators.MaxValueValidator(60)], verbose_name='Широта')),
                ('longtitude', models.FloatField(max_length=20, validators=[django.core.validators.MinValueValidator(30.147), django.core.validators.MaxValueValidator(30.556)], verbose_name='Долгота')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Места',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
