# Generated by Django 4.2.1 on 2023-06-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='lattitude',
            field=models.FloatField(blank=True, default=0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='places',
            name='longtitude',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгота'),
        ),
    ]
