# Generated by Django 4.2.1 on 2023-06-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places_lattitude_places_longtitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='lattitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='places',
            name='longtitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
