# Generated by Django 4.1.7 on 2023-06-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places_lattitude_places_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='lattitude',
            field=models.FloatField(blank=True, default=0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='places',
            name='longitude',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгота'),
        ),
    ]
