# Generated by Django 4.2.1 on 2023-06-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_places_lattitude_alter_places_longtitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='lattitude',
            field=models.CharField(max_length=20, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='places',
            name='longtitude',
            field=models.CharField(max_length=20, verbose_name='Долгота'),
        ),
    ]
