# Generated by Django 4.1.7 on 2023-06-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_places_lattitude_alter_places_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='longitude',
            new_name='longtitude',
        ),
    ]
