# Generated by Django 4.1.7 on 2023-03-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, verbose_name='Почта')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
        ),
    ]
