# Generated by Django 4.1.7 on 2023-06-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='deadline',
            field=models.CharField(choices=[('Не срочно', 'First'), ('Срочно', 'Second'), ('Без срока', 'Third')], default='Не срочно', max_length=10),
        ),
    ]
