# Generated by Django 4.1.7 on 2023-06-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.CharField(choices=[('First', 'Не срочно'), ('Second', 'Срочно'), ('Third', 'Без срока')], default='Обозначить срок...', max_length=20),
        ),
    ]
