# Generated by Django 4.1.7 on 2023-06-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.CharField(choices=[('Не срочно', 'Не срочно'), ('Срочно', 'Срочно'), ('Без срока', 'Без срока')], help_text='Обозначить срок...', max_length=20),
        ),
    ]
