# Generated by Django 4.1.7 on 2023-06-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_tasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='slug',
            field=models.SlugField(),
        ),
    ]
