# Generated by Django 4.1.7 on 2023-06-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_tasks_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('date',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
